### ISSUE TITLE
Compatibility with Puma master branch

### ISSUE THREAD

**Issue by adamlogic** [heroku/barnes#31]
I just attempted to use Puma master, and requests were failing with the following:

```
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `initialize': no implicit conversion of Hash into String (TypeError)
	from /app/vendor/ruby-2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `new'
	from /app/vendor/ruby-2.6.5/lib/ruby/2.6.0/json/common.rb:156:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/multi_json-1.14.1/lib/multi_json/adapters/json_common.rb:14:in `load'
	from /app/vendor/bundle/ruby/2.6.0/gems/multi_json-1.14.1/lib/multi_json/adapter.rb:21:in `load'
	from /app/vendor/bundle/ruby/2.6.0/gems/multi_json-1.14.1/lib/multi_json.rb:122:in `load'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/instruments/puma_instrument.rb:24:in `json_stats'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/instruments/puma_instrument.rb:36:in `instrument!'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/panel.rb:46:in `block in instrument!'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/panel.rb:45:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/panel.rb:45:in `instrument!'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:58:in `block (3 levels) in initialize'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:57:in `block (2 levels) in initialize'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:46:in `loop'
	from /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:46:in `block in initialize'Exception
```

In https://github.com/puma/puma/pull/2086, `Puma.stats` was changed to return a Hash instead of a String. I'm assuming this line needs to be updated to support that.

https://github.com/heroku/barnes/blob/62e99bab7f0f6e5e068372b7cb5a6cf4d16cd66d/lib/barnes/instruments/puma_instrument.rb#L24

**Comment by nateberkopec** [comment]
Puma 5.0 will return a hash here, so I think you should just only attempt JSON conversion if Puma.stats is a `String`.

**Comment by schneems** [comment]
Can we have it give a different API? Maybe `Puma.stats_hash` ?

**Comment by nateberkopec** [comment]
[I think we had a strong case to change it.](https://github.com/puma/puma/commit/1bec245b631baf7e02f18ce2412dc9cca331b6cc) Exposing a string is not extensible by external consumers, which is what this API is intended for. A hash is a much better object for this purpose.

**Comment by schneems** [comment]
A proposal in https://github.com/puma/puma/pull/2253 to expose this as a hash without breaking backward compat.

**Comment by schneems** [comment]
This is resolved
