### ISSUE TITLE
WARNING Thread started in app boot with puma in cluster mode

### ISSUE THREAD

**Issue by grzuy** [heroku/barnes#35]
Hi!

We're getting the following log output when switching to puma cluster mode about a barnes thread starting in app boot.

Do you know if this is something to worry about or something safe to ignore like it was [discussed](https://github.com/rails/rails/issues/37066) for the ActiveRecord one?

``` 
2020-11-02T16:47:56.793226+00:00 app[web.1]: [4] Puma starting in cluster mode...
2020-11-02T16:47:56.793334+00:00 app[web.1]: [4] * Version 5.0.2 (ruby 2.6.6-p146), codename: Spoony Bard
2020-11-02T16:47:56.793364+00:00 app[web.1]: [4] * Min threads: 5, max threads: 5
2020-11-02T16:47:56.793433+00:00 app[web.1]: [4] * Environment: staging
2020-11-02T16:47:56.793467+00:00 app[web.1]: [4] * Process workers: 2
2020-11-02T16:47:56.793499+00:00 app[web.1]: [4] * Preloading application
2020-11-02T16:48:05.004277+00:00 app[web.1]: ** [NewRelic] FATAL : Config file at /app/config/newrelic.yml doesn't include a 'staging' section!
2020-11-02T16:48:05.236417+00:00 app[web.1]: RAILS_ENV=staging environment is not defined in config/webpacker.yml, falling back to production environment
2020-11-02T16:48:09.238369+00:00 app[web.1]: [4] * Listening on http://0.0.0.0:27573
2020-11-02T16:48:09.238587+00:00 app[web.1]: [4] ! WARNING: Detected 2 Thread(s) started in app boot:
2020-11-02T16:48:09.238688+00:00 app[web.1]: [4] ! #<Thread:0x000055f6920dfb68@/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:299 sleep> - /app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `sleep'
2020-11-02T16:48:09.238801+00:00 app[web.1]: [4] ! #<Thread:0x000055f691e92248@/app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:39 sleep> - /app/vendor/bundle/ruby/2.6.0/gems/barnes-0.0.8/lib/barnes/periodic.rb:48:in `sleep'
```

Thanks!

**Comment by schneems** [comment]
That message is just an FYI from puma. You can ignore it.

**Comment by grzuy** [comment]
Gotcha - thanks!
